config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'searches#search'
  resources :users, only: [:index, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :messages, only: :create
  resources :rooms, only: [:create,:show]
end

app/models/add_column_to_user.rb
class AddColumnToUser < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }
  is_impressionable counter_cache: true


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comment, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, excect: [:index, :show]
  impressionist :actions => [:show], unique: [:impressionable_type,:impressionable_id,:session_hash.to_s]

  def index
    to = Time.current
    from = to.ago(7.days)
    @books = Book.includes(:favorited_users)
                      .sort {|a,b|
                        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
                        a.favorited_users.includes(:favorites).where(created_at: from...to).size
                      }
    @book =Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @new_book = Book.new
    @book_user = @book.user
    @user = @book.user
    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_entry.each do |current_user|
        @user_entry.each do |user|
          if current_user.room_id == user.room_id then
            @is_room = true
            @room_id = current_user.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def new
    @book = Book.new
  end

  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(params[:id]), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @user = User.find(params[:id])
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_url)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, excect: [:index, :show, :chat_room]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_entry.each do |current_user|
        @user_entry.each do |user|
          if current_user.room_id == user.room_id then
            @is_room = true
            @room_id = current_user.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/uses_helper.rb
module UsesHelper
end

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="px-3 mx-auto">
        <h1>
          Welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          !
        </h1>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <%= render '/layouts/flash' %>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          !!
        </h1>
        <p>
          In
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          ,
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/user/index.html.erb
<h1>Uses#index</h1>
<p>Find me in app/views/uses/index.html.erb</p>

app/views/user/show.html.erb
<h1>Uses#show</h1>
<p>Find me in app/views/uses/show.html.erb</p>

app/views/users/_chat_btn.html.erb
<% unless user.id == current_user.id %>
  <% if (current_user.following? user) && (user.following? current_user) %>
  <% if is_room == true %>
    <p class="user-chat-room"><a href="/rooms/<%= room_id %>" class="btn btn-primary btn-block">チャットへ</a></p>
  <% else %>
    <%= form_with model: room, local:true do |f| %>
      <%= fields_for entry do |e| %>
        <%= e.hidden_field :user_id, value: user.id %>
      <% end %>
      <%= f.submit "チャットを始める", class: "btn btn-primary btn-block user-show-chat" %>
    <% end %>
  <% end %>
  <% end %>
<% end %>

app/views/users/_follow_btn.html.erb
<% if current_user.following?(user) %>
  <%= link_to 'フォローを外す', user_relationship_path(user.id), method: :delete, class: 'btn btn-info btn-block' %>
<% else %>
  <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, class: 'btn btn-success btn-block' %>
<% end %>

app/views/users/_user_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size: "100x100" %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%= link_to user.followings.count, user_followings_path(user) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.followers.count, user_followers_path(user) %></th>
    </tr>
  </tbody>
</table>
<div>
  <% if current_user.id == user.id %>
    <%= link_to "", edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user" %>
  <% else %>
    <%= render '/users/follow_btn', user: @user %>
  <% end %>
  <%= render 'users/chat_btn', {user: @user, is_room: @is_room, room_id: @room_id, room: @room, entry: @entry} %>
</div>

app/views/users/_user_search.html.erb
<thead>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Introduction</th>
    <th>Follows</th>
    <th>Followers</th>
  </tr>
</thead>
<tbody>
  <tr>
    <% users.each do |user| %>
      <td>
        <%= link_to user_path(user) do %>
          <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40" %>
        <% end %>
      </td>
      <td>
        <%= link_to user_path(user) do %>
          <%= user.name %>
        <% end %>
      </td>
      <td><%= user.introduction %></td>
      <td><%= user.followings.count %></td>
      <td><%= user.followers.count %></td>
    <% end %>
  </tr>
</tbody>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model:@user, local: true do |f| %>
        <%= render '/layouts/errors', model: @user %>
          <div class="form-group">
            <%= f.label :name %></br>
            <%= f.text_field :name, class: "form-control"%>
          </div>
          <div class="form-group">
            <%= f.label :profile_image, "image" %></br>
            <%= f.attachment_field :profile_image %>
          </div>
          <div class="form-group">
            <%= f.label :introduction %></br>
            <%= f.text_area :introduction, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render '/users/user_info', user: @user %>
        <%= render '/books/new', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= link_to user_path(user.id) do %>
                    <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40" %>
                  <% end %>
                </td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.followings.count %></td>
                <td>フォロワー数：<%= user.followers.count %></td>
                <td>
                  <% unless user.id == current_user.id %>
                    <% if current_user.following?(user) %>
                      <%= link_to 'フォローを外す', user_relationship_path(id: user.id, user_id: user.id), method: :delete %>
                    <% else %>
                      <%= link_to 'フォローする', user_relationships_path(id: user.id, user_id: user.id), method: :post %>
                    <% end %>
                  <% end %>
                </td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <%= render '/layouts/flash' %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render '/users/user_info', user: @user %>
        <%= render '/books/new', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <%= render '/books/books', books: @books %>
      </div>
    </div>
  </div>
</main>